
services:
  web:
    image: mx/website
    build:
      context: ./website
      dockerfile: Dockerfile
      target: dev
      args:
        NODE_VERSION: 18.7
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./website/app:/app
    ports:
      - "5173:5173"
    command: "npm run dev"